### ISSUE TITLE
Introduce Automatic releasing to GooglePlay

### ISSUE THREAD

**Issue by wakwak3125** [DroidKaigi/conference-app-2017#222]
# Overview(Required)
refs: https://www.youtube.com/watch?v=L_QVB4Qdh6o

Release flow has many things to do. So I think it should be automated.

- Uploading APK
- Updating changelogs for each languages.
- Uploading mapping file to crash reporting service like Firebase Crash Reporting or Crashlytics.
- Also screenshots are should be updated if it has update.

# Details 

## Must(I think it's minimum composition.)
- Use `Supply` from Fastlane to upload apk file and changelogs. 
- Upload `mapping.txt` to Firebase Crash Reporting via gradle plugin.
- Use Gradle task to kick Automated releasing locally.

### TASKS
- [ ] Create deploying shell to GooglePlay.
- [ ] Introduce mapping file uploading plugin.
- [ ] Create deploying GradleTask.

## Optional
- Take screenshot automaticaly by Fastlane's feature and Espresso for every release.
- Kick Automated relesing by merge master branch.

## LInk
https://github.com/fastlane/fastlane
https://firebase.google.com/docs/crash/android?hl=en
https://github.com/fastlane/fastlane/tree/master/supply

What do you think about them?

**Comment by konifar** [comment]
Cool 🆒 Interesting.
I guess it's related to your DroidKaigi session, right?
I would be happy if you will tackle this 😄

**Comment by wakwak3125** [comment]
Exactly! I'll start them!
