### ISSUE TITLE
Create Contributors page

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2017#78]
Assigned to @shiraji

## Overview (Required)
- For great contributors, I want to create Contributors page.
- It would be good to show many contributors in one page.
- GridView is better than ListView?

## Links
- https://github.com/konifar/droidkaigi2016/blob/master/app/src/main/java/io/github/droidkaigi/confsched/activity/ContributorsActivity.java#L72

**Comment by shiraji** [comment]
do you have a concreate design for this page?

**Comment by konifar** [comment]
@shiraji Yes, but it's only in my mind. I'll put the paper design here.

**Comment by shiraji** [comment]
Thanks!

**Comment by konifar** [comment]
@shiraji 
<img src="https://cloud.githubusercontent.com/assets/1269214/22631465/43f76070-ec51-11e6-9c4b-e7cf341944e3.png" width="300" />

- Column 3 grid. Grid is better than List to show many contributors in one page.
- name TextView 14sp, lines="2". You can use `@style/TextBody`
- avator ImageView 60dp.
- Base margin 16dp. You can use `@dimen/space_16dp`

**Comment by srym** [comment]
Is @shiraji going to take this ticket?

**Comment by shiraji** [comment]
Sure but I might be too slow to complete this issue. You can help me out.

Here is what I think we need to do for this issue.

# TODO

- [ ] Create ContributorsRemoteDataSource [sample](https://github.com/konifar/droidkaigi2016/blob/master/app/src/main/java/io/github/droidkaigi/confsched/api/DroidKaigiClient.java#L88)
- [ ] Create ContributorsLocalDataSource using Orma
- [ ] Create ContributorsRepository having above 2 classes (check SessionsRepository)
- [ ] Modify ContributorsViewModel to fetch contributors data
- [ ] Add layout using GridView to ContributorsFragment
- [ ] Add typo for later contributors!

**Comment by konifar** [comment]
>  Add typo for later contributors!

😄

**Comment by srym** [comment]
@shiraji Oh I just want to clarify who is do this task, otherwise I would have made duplicate contribution!
I'd love to help you. What do you think is the best way to collaborate each other? Should I make PR to your forked repository?

**Comment by shiraji** [comment]
Sure. I haven't done anything, yet, thou.

**Comment by shiraji** [comment]
Here is the branch https://github.com/shiraji/conference-app-2017/tree/add_contributor_page

**Comment by shiraji** [comment]
Or @konifar do you want us to send PR in each feature? Like sending PR of [this commit ](https://github.com/shiraji/conference-app-2017/commit/4adfcf43bc2f0fc84b531b1559889b7e9e124616)

I think this issue will create a huge PR. If you don't want that I can send PR in the small amount of features.

**Comment by konifar** [comment]
Either is fine. But if you can, smaller PR (step by steps) sounds better.

**Comment by shiraji** [comment]
Close for now?

**Comment by konifar** [comment]
@shiraji @srym @nshida Thank you so much!!
